db.movies.save({"title":"The Lord of the Rings: The Fellowship of the Ring","details": {"year":"2001","rated":"PG-13","genre":["Adventure", "Drama", "Fantasy"],"director":"Peter Jackson",},"actors":["Alan Howard", "Noel Appleby", "Sean Astin", "Sala Baker"],"plot":"A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle Earth from the Dark Lord Sauron.","imdbRating":8.8,"boxOffice":"$314,000,000"})

db.movies.save({"title":"X-Men","details": {"year":"2000","rated":"PG-13","genre":["Action", "Adventure", "Sci-Fi"],"director":"Bryan Singer",},"actors":["Hugh Jackman", "Patrick Stewart", "Ian McKellen", "Famke Janssen"],"plot":"Two mutants come to a private academy for their kind whose resident superhero team must oppose a terrorist organization with similar powers.","imdbRating":7.4,"boxOffice":"$156,164,829"})

db.movies.save({"title":"Batman","details": {"year":"1989","rated":"PG-13","genre":["Action", "Adventure"],"director":"Tim Burton",},"actors":["Michael Keaton", "Jack Nicholson", "Kim Basinger", "Robert Wuhl"],"plot":"The Dark Knight of Gotham City begins his war on crime with his first major enemy being the clownishly homicidal Joker.","imdbRating":7.6})

db.movies.save({"title":"Iron Man","details": {"year":"2008","rated":"PG-13","genre":["Action", "Adventure", "Sci-Fi"],"director":"Jon Favreau",},"actors":["Robert Downey Jr.", "Terrence Howard", "Jeff Bridges", "Gwyneth Paltrow"],"plot":"After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.","imdbRating":"7.9","boxOffice":"$318,298,180"})

db.movies.save({"title":"Wonder Woman","details": {"year":"2017","rated":"PG-13","genre":["Action", "Adventure", "Fantasy"],"director":"Patty Jenkins",},"actors":["Gal Gadot", "Robin Wright", "David Thewlis", "Connie Nielsen"],"plot":"Before she was Wonder Woman she was Diana, princess of the Amazons, trained warrior. When a pilot crashes and tells of conflict in the outside world, she leaves home to fight a war to end all wars, discovering her full powers and true destiny.","imdbRating":8.4})

db.movies.save({"title":"Star Wars: Episode IV - A New Hope","details": {"year":"1977","rated":"PG","genre":["Action", "Adventure", "Fantasy"],"director":"George Lucas",},"actors":["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Peter Cushing"], "plot":"Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a wookiee and two droids to save the galaxy from the Empire's world-destroying battle-station, while also attempting to rescue Princess Leia from the evil Darth Vader.","imdbRating":8.7})

db.movies.save({"title":"I, Robot","details": {"year":"2004","rated":"PG-13","genre":["Action", "Crime", "Drama"],"director":"Alex Proyas",},"actors":["Will Smith", "Bridget Moynahan", "Alan Tudyk", "James Cromwell"],"plot":"In 2035, a technophobic cop investigates a crime that may have been perpetrated by a robot, which leads to a larger threat to humanity.","imdbRating":7.1})

db.movies.save({"title":"Spider-Man","details": {"year":"2002","rated":"PG-13","genre":["Action", "Adventure"],"director":"Sam Raimi",},"actors":["Tobey Maguire", "Willem Dafoe", "Kirsten Dunst", "James Franco"],"plot":"When bitten by a genetically modified spider, a nerdy, shy, and awkward high school student gains spider-like abilities that he eventually must use to fight evil as a superhero after tragedy befalls his family.","imdbRating":7.3,"boxOffice":"$403,706,375"})

db.movies.save({"title":"Fantastic Four","details": {"year":"2005","rated":"PG-13","genre":["Action", "Adventure", "Family"],"director":"Tim Story",},"actors":["Ioan Gruffudd", "Jessica Alba", "Chris Evans", "Michael Chiklis"],"plot":"A group of astronauts gain superpowers after a cosmic radiation exposure and must use them to oppose the plans of their enemy, Doctor Victor Von Doom.","imdbRating":5.7,"boxOffice":"$154,485,963"})

db.movies.save({"title":"The Hobbit: An Unexpected Journey","details": {"year":"2012","rated":"PG-13","genre":["Adventure", "Fantasy"],"director":"Peter Jackson",},"actors":["Ian McKellen", "Martin Freeman", "Richard Armitage", "Ken Stott"],"plot":"A reluctant hobbit, Bilbo Baggins, sets out to the Lonely Mountain with a spirited group of dwarves to reclaim their mountain home - and the gold within it - from the dragon Smaug.","imdbRating":7.9,"boxOffice":"$303,001,229"})

db.movies.save({"title":"The Avengers","details": {"year":"2012","rated":"PG-13","genre":["Action", "Sci-Fi"],"director":"Joss Whedon",},"actors":["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth"],"plot":"Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.","imdbRating":8.1,"boxOffice":"$623,279,547"})

db.movies.save({"title":"The Incredibles","details": {"year":"2004","rated":"PG","genre": ["Animation"],"director":"Brad Bird",},"actors":["Craig T. Nelson", "Samuel L. Jackson"],"plot":"A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world.","imdbRating":8.0})
